### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by sebbourgeois** [alexlaverty/python-reddit-youtube-bot#100]
Hey @alexlaverty (_happy new year !_),

Seems they did some change (again) on the login page : 
`Downloading screenshots of reddit posts...
Launching Headless Browser...
Username and password fields not found.
Login failed.
Downloading screenshots... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 440, in <module>
    process_submissions(submissions)
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 64, in process_submissions
    process_submission(submission)
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 118, in process_submission
    vid.create(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/video_generation/video.py", line 500, in create
    download_screenshots_of_reddit_posts(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/comments/screenshot.py", line 179, in download_screenshots_of_reddit_posts
    page.locator(f"#t1_{comment.id}").screenshot(path=comment_path)
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 17227, in screenshot
    self._sync(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 491, in screenshot
    return await self._with_element(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 103, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 297, in element_handle
    handle = await self._frame.wait_for_selector(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 322, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("#t1_khe3o65")
============================================================
`

Tried with accounts that have access to both old and new UI, same error (#t1_khe3o65 for old UI, #t1_khjepkk for new UI)

**Comment by johnnyvng** [comment]
I got the same issue

Downloading screenshots of reddit posts...
Launching Headless Browser...
Traceback (most recent call last):
  File "/mnt/hgfs/sharedVMware/tt_PEOPLE-BLOG/PEOPLE-BLOG-1-AmItheAsshole/app.py", line 369, in <module>
    process_submissions(submissions)
  File "/mnt/hgfs/sharedVMware/tt_PEOPLE-BLOG/PEOPLE-BLOG-1-AmItheAsshole/app.py", line 64, in process_submissions
    process_submission(submission)
  File "/mnt/hgfs/sharedVMware/tt_PEOPLE-BLOG/PEOPLE-BLOG-1-AmItheAsshole/app.py", line 115, in process_submission
    vid.create(
  File "/mnt/hgfs/sharedVMware/tt_PEOPLE-BLOG/PEOPLE-BLOG-1-AmItheAsshole/video_generation/video.py", line 476, in create
    download_screenshots_of_reddit_posts(
  File "/mnt/hgfs/sharedVMware/tt_PEOPLE-BLOG/PEOPLE-BLOG-1-AmItheAsshole/comments/screenshot.py", line 70, in download_screenshots_of_reddit_posts
    page.type("#loginUsername", auth.praw_username)
  File "/home/aibots/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 11470, in type
    self._sync(
  File "/home/aibots/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/home/aibots/.local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 910, in type
    return await self._main_frame.type(**locals_to_params(locals()))
  File "/home/aibots/.local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 710, in type
    await self._channel.send("type", locals_to_params(locals()))
  File "/home/aibots/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/home/aibots/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/home/aibots/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("#loginUsername")

**Comment by alexlaverty** [comment]
Feels like reddit is purposely trying to break 3rd party apps these days... I'm away on leave at the moment will have a look when I'm back next week.

**Comment by alexlaverty** [comment]
In the screenshot.py you can change headless to false and it'll show the chrome browser as it scrapes the comments might give a clue as to what's wrong

**Comment by alexlaverty** [comment]
Doing some investigation tonight, seems running it from Github Actions I'm getting the following error, will keep troubleshooting to see if there's any way around it...  :

![image](https://github.com/alexlaverty/python-reddit-youtube-bot/assets/4024404/e3dd9a0c-a412-4eca-a430-6e1a1a9b8db7)

**Comment by sebbourgeois** [comment]
Hey Alex,

Yeah, I have the same result when I run the command in my terminal : 
`Launching Headless Browser...
Username and password fields not found. Printing HTML:
<!DOCTYPE html><html><head>
    <title>Blocked</title>
    <style>
      body {
          font: small verdana, arial, helvetica, sans-serif;
          width: 600px;
          margin: 0 auto;
      }

      h1 {
          height: 40px;
          background: transparent url(//www.redditstatic.com/reddit.com.header.png) no-repeat scroll top right;
      }
    </style>
  </head>
  <body>
    <h1>whoa there, pardner!</h1>

<p>Your request has been blocked due to a network policy.</p>

<p>Try logging in or creating an account <a href="https://www.reddit.com/login/">here</a> to get back to browsing.</p>

<p>If you're running a script or application, please register or sign in with your developer credentials <a href="https://www.reddit.com/wiki/api/">here</a>. Additionally make sure your User-Agent is not empty and is something unique and descriptive and try again. if you're supplying an alternate User-Agent string,
try changing back to default as that can sometimes result in a block.</p>

<p>You can read Reddit's Terms of Service <a href="https://www.reddit.com/wiki/api/">here</a>.</p>

<p>if you think that we've incorrectly blocked you or you would like to discuss
easier ways to get the data you want, please file a ticket <a href="https://support.reddithelp.com/hc/en-us/requests/new?ticket_form_id=21879292693140">here</a>.</p>

<p>when contacting us, please include your ip address which is: <strong>141.8.90.120</strong> and reddit account</p>


    </body></html>
Login failed.
`

They are really making it hard and annoying these days

**Comment by sebbourgeois** [comment]
@alexlaverty I just made a PR (https://github.com/alexlaverty/python-reddit-youtube-bot/pull/101) to fix that issue. Enforcing the user agent works like a charm. Also made a change in the requirements.txt to enforce Pillow to v9.5.0, latest version (10+) throws errors.

**Comment by alexlaverty** [comment]
Nice work with the PR i have merged it in, for the comment larger than video height error the code is :

```
  if img_clip.h > settings.video_height:
      logging.info("Comment larger than video height : %s", img_path)
      continue
```
https://github.com/alexlaverty/python-reddit-youtube-bot/blob/38de9b628c2869bc00983b56f9c398602bee145a/video_generation/video.py#L542-L544

Basically if the comment height is bigger then height of the video skip it, maybe check what your video_height is set to or how big the images are i will run with the latest from master and see if i can reproduce.
