### ISSUE TITLE
App not starting anymore

### ISSUE THREAD

**Issue by sebbourgeois** [alexlaverty/python-reddit-youtube-bot#78]
I just made a pull request some minutes ago to get the latest changes, and I now have this erro rwhenever I run the app.py : 

```Traceback (most recent call last):
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 15, in <module>
    import video_generation.video as vid
  File "/home/sb/videos-creation/python-reddit-youtube-bot/video_generation/video.py", line 37, in <module>
    import publish.youtube as youtube
  File "/home/sb/videos-creation/python-reddit-youtube-bot/publish/youtube.py", line 9, in <module>
    from simple_youtube_api.youtube_video import YouTubeVideo
ModuleNotFoundError: No module named 'simple_youtube_api.youtube_video'
```

I did update the latest pip modules as well, but no change.

**Comment by alexlaverty** [comment]
could you pull again, i've just merged this PR to fix some issues :
https://github.com/alexlaverty/python-reddit-youtube-bot/pull/77

**Comment by sebbourgeois** [comment]
Yep, all good, thanks a lot !
