### ISSUE TITLE
New timeout issue during downloading screenshots of reddit posts

### ISSUE THREAD

**Issue by sebbourgeois** [alexlaverty/python-reddit-youtube-bot#89]
I tried to increase the timeout to 90000, seems it keeps trying 30000ms anyway

```Downloading screenshots of reddit posts...
Launching Headless Browser...
Traceback (most recent call last):
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 369, in <module>
    process_submissions(submissions)
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 64, in process_submissions
    process_submission(submission)
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 115, in process_submission
    vid.create(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/video_generation/video.py", line 476, in create
    download_screenshots_of_reddit_posts(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/comments/screenshot.py", line 73, in download_screenshots_of_reddit_posts
    page.wait_for_url("https://www.reddit.com/")
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 9379, in wait_for_url
    self._sync(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_page.py", line 519, in wait_for_url
    return await self._main_frame.wait_for_url(**locals_to_params(locals()))
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 232, in wait_for_url
    async with self.expect_navigation(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_event_context_manager.py", line 33, in __aexit__
    await self._future
  File "/home/sb/videos-creation/python-reddit-youtube-bot/env/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 208, in continuation
    event = await wait_helper.result()
playwright._impl._api_types.TimeoutError: Timeout 30000.0ms exceeded.
=========================== logs ===========================
waiting for navigation to "https://www.reddit.com/" until 'load'
============================================================

**Comment by sebbourgeois** [comment]
Nevermind, the issue was coming from my reddit account, not from the script !
