### ISSUE TITLE
How can I add background music to a video?

### ISSUE THREAD

**Issue by alexdo83** [alexlaverty/python-reddit-youtube-bot#94]
How can I add background music to a video?

**Comment by sebbourgeois** [comment]
On my end, I have a "post-treatment" script that I use on every video generated, that adds copyright free music in the background.

**Comment by alexlaverty** [comment]
Have pushed some updates, pull the latest code and try these out :

Enable background music that will be randomly selected from the `assets/music` folder :

```
python app.py --enable-background-music
```

Specify a file to use as the background music 

```
python app.py --background-music-path "E:\Music\Colter Wall - Cowpoke.mp3"
```

**Comment by sebbourgeois** [comment]
@alexlaverty I started today trying that new feature. 
First video generated, got an error : 
```
Creating background music audio
2023-11-19 12:08:46 INFO     Randomly Selected Background Music : assets/music/Across the Savannah - Aaron Kenny.mp3
Traceback (most recent call last):
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 440, in <module>
    process_submissions(submissions)
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 64, in process_submissions
    process_submission(submission)
  File "/home/sb/videos-creation/python-reddit-youtube-bot/app.py", line 118, in process_submission
    vid.create(
  File "/home/sb/videos-creation/python-reddit-youtube-bot/video_generation/video.py", line 779, in create
    background_music_audio = background_music_audio.volumex(0).loop(-1, duration=v.duration)
AttributeError: 'AudioFileClip' object has no attribute 'loop'

```

**Comment by alexlaverty** [comment]
can you share the reddit url and the command you used to generate, will try to reproduce
